### ISSUE TITLE
Program navigates to the seller's info instead of buying out the car

### ISSUE THREAD

**Issue by Z571144** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#10]
First of all, thank you for developing this software that attempts to reduce the time needed for me to sit in front of my pc.
However, the program navigates to show the seller's Xbox info instead of buying out the car, it then stays still on that screen.
I suppose it is because of the program pressing the down arrow key once more than it originally needed to buy out the car.
I am using a 1080p 144hz monitor and running the 1.1.1 .exe file for the software, both the resolution for the game and the pc were set to 1920x1080 and 144hz.

Please help, thanks a lot.

**Comment by Scruffydrew** [comment]
Sorry for the late reply and thanks for letting me know ill start looking into it now

**Comment by Z571144** [comment]
[logfile.log](https://github.com/Scruffydrew/Forza-Horizon-5-Auction-House-Sniper/files/10845574/logfile.log)
Sorry for the late reply, here is the log file.

**Comment by Scruffydrew** [comment]
ok thanks im having a look at it now

**Comment by Scruffydrew** [comment]
I wasnt able to replicate your issue on my end but still, I've added a check for when it presses the down key, that should fix the issue.
Let me know how if that fixes the issue :)
https://github.com/Scruffydrew/Forza-Horizon-5-Auction-House-Sniper/releases/tag/v1.1.2

**Comment by kogami23** [comment]
I got the exact same issue - the program goes straight to third option istead of 2nd one (buy out).

**Comment by Scruffydrew** [comment]
does the program just stop on the third option or does it press enter, also message me on discord for a quicker response my discord is Scruffydrew

**Comment by Scruffydrew** [comment]
also make sure you searching the auction house from a festival site and not a house
