### ISSUE TITLE
Stuck at "Search Auctions"

### ISSUE THREAD

**Issue by ghost** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#11]
1080p, 60hz, no HDR, and fullscreen
language is English
and getting "line 50"

**Comment by Scruffydrew** [comment]
is your brightness set to 50?

**Comment by toHex16** [comment]
Now it goes to the seller's info instead of buy the car

**Comment by Temnelc** [comment]
Hello, I also have the same problem as OP. Nothing happens when I launch the program and click back to FH5.
I have a 1080p, 120Hz, No HDR Monitor, but the game is running on 60Hz with english language and my monitor brightness is set at 50.

**Comment by Scruffydrew** [comment]
Is your resolution 16:9?

**Comment by Temnelc** [comment]
> Is your resolution 16:9?

Yes, 1920x1080 screen

**Comment by Scruffydrew** [comment]
Try the latest release
