### ISSUE TITLE
Doesnt even enter the search to look for car

### ISSUE THREAD

**Issue by TheGuestRoblox** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#17]
When i start the program, I put my cursor to the side where it wont randomly click anything. In the top left, it says its starting search, but doesn't do anything.

**Comment by TioHerman** [comment]
if this happens, click on the screen to enter the auction house filter then quickly back out, this normally fix it for me

**Comment by TheGuestRoblox** [comment]
![Screenshot 2024-05-01 173101](https://github.com/Scruffydrew/Forza-Horizon-5-Auction-House-Sniper/assets/99096284/d493c737-e863-4bb1-b58c-1fcb1e2a1f59)
this is what it looks like when i boot it up

**Comment by TheGuestRoblox** [comment]
Scruffy told me to run it as an administrator. It fixed the problem.
