### ISSUE TITLE
Advanced search sniping?

### ISSUE THREAD

**Issue by TioHerman** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#18]
It's possible to do an version which can snipe using the advanced search?  some brands can have multiple cars filtered down by certain parameters (like you can snipe both lancia 037 and delta S4 by filtering for 1980)

**Comment by Scruffydrew** [comment]
id have to look into it but if i do make a version that can then i'd probably do it for a new version of the program that i have been working on that should be a little faster. but i still need to fix some bugs in my new program. but if you would like to get this new version and find and let me know of any bugs that you find i can send you the program. just message me on discord. my username is scruffydrew

**Comment by TioHerman** [comment]
> id have to look into it but if i do make a version that can then i'd probably do it for a new version of the program that i have been working on that should be a little faster. but i still need to fix some bugs in my new program. but if you would like to get this new version and find and let me know of any bugs that you find i can send you the program. just message me on discord. my username is scruffydrew

I've added you, my name is the same from here

**Comment by StewedLawyer9** [comment]
also adds you, I would ask you to send the program. My nick on discord is : rogowski_1337
