### ISSUE TITLE
Program execution problem

### ISSUE THREAD

**Issue by FunnyinGitHub** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#19]
win11, my computer screen is 16:10, when I changed the computer resolution to 1920x1080 in the Settings, and set the game resolution to 1920x1080, the brightness is 50, the frame number is unlimited, the frame number is maintained at about 110, turn off Nvidia's in-game coverage. After the program is executed, the mouse is placed in the upper left corner, and the screen has no reaction. The program starts to execute only after manually clicking enter, but it will only repeat twice, and then there will be no reaction. The program will be executed again only after manually clicking esc and enter, but it will still be executed twice.

**Comment by TheGuestRoblox** [comment]
yup, same thing happened to me. i think there may be a bug in the code

**Comment by Scruffydrew** [comment]
As far as i know there isnt any bugs in the code, but if you would like message me on discord and ill see if i can help you out. my username is scruffydrew

**Comment by TheGuestRoblox** [comment]
> win11, my computer screen is 16:10, when I changed the computer resolution to 1920x1080 in the Settings, and set the game resolution to 1920x1080, the brightness is 50, the frame number is unlimited, the frame number is maintained at about 110, turn off Nvidia's in-game coverage. After the program is executed, the mouse is placed in the upper left corner, and the screen has no reaction. The program starts to execute only after manually clicking enter, but it will only repeat twice, and then there will be no reaction. The program will be executed again only after manually clicking esc and enter, but it will still be executed twice.

Scruffy told me to run it as an administrator. It fixed the problem.

**Comment by FunnyinGitHub** [comment]
> > win11，我的电脑屏幕是16：10，当我在设置中将电脑分辨率更改为1920x1080时，将游戏分辨率设置为1920x1080，亮度为50，帧数不受限制，帧数保持在110左右，关闭Nvidia的游戏内覆盖。程序执行后，鼠标放在左上角，屏幕没有反应。程序只有在手动按回车键后才开始执行，但只会重复两次，然后不会有任何反应。只有在手动单击 esc 并回车后，程序才会再次执行，但仍会执行两次。
> 
> 邋遢告诉我以管理员身份运行它。它解决了问题。

I still can't solve it......

**Comment by Scruffydrew** [comment]
Send me a message on discord and ill see if i can help. my user is scruffydrew

**Comment by rlryxn** [comment]
> > > win11，我的电脑屏幕是16：10，当我在设置中将电脑分辨率更改为1920x1080时，将游戏分辨率设置为1920x1080，亮度为50，帧数不受限制，帧数保持在110左右，关闭Nvidia的游戏内覆盖。程序执行后，鼠标放在左上角，屏幕没有反应。程序只有在手动按回车键后才开始执行，但只会重复两次，然后不会有任何反应。只有在手动单击 esc 并回车后，程序才会再次执行，但仍会执行两次。
> > 
> > 
> > 邋遢告诉我以管理员身份运行它。它解决了问题。
> 
> I still can't solve it......

and you ran it as an admin? you went to your file explorer, and ran the .exe as a admin? well if it still isnt working maybe you have an outdated version? redownload the file maybe?
