### ISSUE TITLE
how do i package the code into exe file

### ISSUE THREAD

**Issue by seeG99** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#24]
I want to add a slight delay between the first 2 enters. Sometimes the 2nd enter is pressed too quickly and the program gets stuck on the filter screen. i change the time sleep between the 2 enters but i am not able to save the code into an exe file

**Comment by FromNowOnJenny** [comment]
you could use nuitka to compile the python code into a binary

**Comment by Scruffydrew** [comment]
I use auto-py-to-exe to compile the python code into an exe
