### ISSUE TITLE
it doent hit inther when bet failed

### ISSUE THREAD

**Issue by IWantToBeBlue** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#3]
![unknown111](https://user-images.githubusercontent.com/95884925/179232291-cef19ad2-805a-46c0-b6da-9d0cacfc7dc7.png)
can you do so that it press enter when this comes up 
and can you maybe make it faster

**Comment by Scruffydrew** [comment]
i should be able to make it press enter then but i wont have time tonight and will have to do it tomorrow.
and about making it faster, was there any specific part of the process where you felt it needed to be faster?

**Comment by Scruffydrew** [comment]
ive updated it to include the buyout failed screen, but making it faster will require some testing

**Comment by Scruffydrew** [comment]
sorry for taking so long to do the testing, i still havent gotten around to actually spending some time testing it, i havent had much time lately as i got a bunch of assignments and shit that i gotta do, so i expect it wont be for a few weeks until i am able to find some time to do some testing.
again sorry for the inconvenience

**Comment by IWantToBeBlue** [comment]
it fine 
the speed is because the car is often bought before the bot buys it, I know it cant be a 100% purchase but right now it is almost = 0 if u cant fix it then its ok

**Comment by Scruffydrew** [comment]
ill see if i can find some time to do a bunch of testing, but if i cant then i should be able to do it after the 31 this month so in like 1.5 weeks i should be all good as ive basically complete the rest of my assignments and shit
sorry for the inconvenience.

**Comment by Scruffydrew** [comment]
I've updated the program, it should be faster when it comes to selecting the listing, you can download it from the releases page, if you have any issues please let me know
