### ISSUE TITLE
Script not pressing any keys and log file is empty

### ISSUE THREAD

**Issue by christianhals** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#4]
Are there any additonal software required to run this on Windows 10?

My system and keyboard language is set to English US. The program starts and I can see the overlay, but the script is not doing any keyboard presses. The logfile is empty and tried with both latest releases.

Any suggestions would be appreciated.

**Comment by Scruffydrew** [comment]
Once the overlay has appeared you may need click back into Forza Horizon 5, let me know if that fixes your issue

**Comment by Scruffydrew** [comment]
ive also just uploaded a dev version which should fix the issue with the logfile

**Comment by Scruffydrew** [comment]
Check out the latest version i just released, it should now wait until Forza Horizon 5 is the active window

**Comment by christianhals** [comment]
It seems to be an issue with Logitech Options. I just uninstalled the application and I´m now sniping away:-)

Crazy how fast these cars are appearing/dissapearing. The script has already found more than 20 cars for sale within my max price and model, but haven´t successfully gotten any yet. Hopefully I will get there in the end. Just missing 4 cars from the early series.

Thanks again for sharing this excellent script and your assistance.
