### ISSUE TITLE
Having this same issue, tried everything

### ISSUE THREAD

**Issue by itchyy** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#6]
Visual settings match your image in the issue thread, i've tried running it as admin, only ever getting "Line: 50" over and over.

![Skærmbillede 2022-07-15 142831](https://user-images.githubusercontent.com/95884925/179223007-569dbe0d-fa07-46b4-8da9-026c28ef005d.png)

_Originally posted by @IWantToBeBlue in https://github.com/Scruffydrew/Forza-Horizon-5-Auction-House-Sniper/issues/1#issuecomment-1185497635_

**Comment by Scruffydrew** [comment]
Hey, thanks for letting me know
Just to clarify you have your brightness set to 50 and have hdr off
Correct?

**Comment by itchyy** [comment]
yep. hdr off, brightness at 50, even set resolution to 1080p from 1440 just to see if that would do it.

**Comment by Scruffydrew** [comment]
Is your game on  fullscreen

**Comment by itchyy** [comment]
yea, i've turned off all the overlays i could find as well

**Comment by Scruffydrew** [comment]
Can you send me a screenshot of your game when the program is stuck

**Comment by itchyy** [comment]
![image](https://user-images.githubusercontent.com/112335275/187085155-32d51703-6910-463c-a779-241fbf3f117d.png)

**Comment by Scruffydrew** [comment]
You got an ultra wide monitor? That might be causing the issue maybe

**Comment by Scruffydrew** [comment]
If you want me to add support for ultra wide then I'm goimg to need your help to get some values. If your happy to help then send me a friend request on discord and we can work out what I need you to do
My discord is Scruffydrew#2909

**Comment by Scruffydrew** [comment]
Also the issue could be with what the resolution is set to in windows

**Comment by itchyy** [comment]
I got it working i dunno what i did exactly because changing the resolution in windows didn't work either, i changed it to 1600x900, and set all my settings to very low, and for some reason it started working.

**Comment by Scruffydrew** [comment]
Ok great
