### ISSUE TITLE
program crashes the game

### ISSUE THREAD

**Issue by den1scho** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#9]
Hey, so I ran the program while I was in forza but instead it crashed the game and it kept on spamming Line: 50. I'm using the latest 1.1.1 version. I tried it multiple times and it kept on crashing my game.

**Comment by den1scho** [comment]
I start the program, it gets monitor info and then as soon as it says program running forza closes

**Comment by Scruffydrew** [comment]
I wasn't able to replicate the issue your having, I was however able to replicate it when I ran the raw code. So if your running the raw code make sure you use the application. Apart from that idk what to do. I'm not really sure what is causing the issue.  But in the mean time use the latest version of the script.
